export const alarmDummy = [
  {
    id: 1,
    category: "행사",
    type: "D-Day",
    dDay: 1,
    time: "몇분전",
    title: "어르신 지원정책 모음",
    description: "노인 생활안전사고 예방 지원정책",
    read: true,
  },
  {
    id: 2,
    category: "행사",
    type: "환영인사",
    dDay: 3,
    time: "1시간 전",
    title: "환영합니다!",
    description: "<everguide 가이드> 읽어보기",
    read: false,
  },
  {
    id: 3,
    category: "공지",
    type: "D-Day",
    dDay: 5,
    time: "3시간 전",
    title: "소상공인 지원 정책",
    description: "소상공인을 위한 대출 및 지원 정보 제공",
    read: false,
  },
  {
    id: 4,
    category: "교육",
    type: "D-Day",
    dDay: 0,
    time: "방금",
    title: "무료 코딩 교육",
    description: "기초부터 배우는 무료 온라인 코딩 교육 과정",
    read: false,
  },
  {
    id: 5,
    category: "이벤트",
    type: "D-Day",
    dDay: 7,
    time: "2일 전",
    title: "환경 보호 캠페인",
    description: "지구를 살리는 친환경 실천 이벤트",
    read: false,
  },
  {
    id: 6,
    category: "공지",
    type: "D-Day",
    dDay: 10,
    time: "5일 전",
    title: "주거 지원 정책 안내",
    description: "청년 및 신혼부부를 위한 주거 지원 정책 정리",
    read: true,
  },
  {
    id: 7,
    category: "행사",
    type: "D-Day",
    dDay: 2,
    time: "1일 전",
    title: "문화 예술 축제",
    description: "전국 주요 도시에서 열리는 문화 예술 축제 일정",
    read: false,
  },
  {
    id: 8,
    category: "교육",
    type: "D-Day",
    dDay: 14,
    time: "6일 전",
    title: "AI 기초 강의",
    description: "인공지능 개념 및 활용법을 배울 수 있는 무료 강의",
    read: false,
  },
  {
    id: 9,
    category: "이벤트",
    type: "D-Day",
    dDay: 20,
    time: "1주일 전",
    title: "독서 캠페인",
    description: "책 읽기 장려를 위한 독서 캠페인 진행 안내",
    read: false,
  },
  {
    id: 10,
    category: "행사",
    type: "D-Day",
    dDay: 30,
    time: "2주 전",
    title: "전국 마라톤 대회",
    description: "건강 증진을 위한 전국 마라톤 대회 개최 일정 안내",
    read: true,
  },
];