export const dummyData = [
  {
    id: 1,
    title: "어르신 지원정책 모음",
    subTitle: "노인 생활안전사고 예방 지원정책",
    bookMark: false,
    category: "복지",
    content: "지원내용: 노인 생활 안전사고 예방을 위한 맞춤형 지원 제공",
  },
  {
    id: 2,
    title: "어르신 복지서비스",
    subTitle: "노인 대상 복지 혜택 모음",
    bookMark: true,
    category: "보건",
    content: "지원내용: 노인 복지를 위한 다양한 혜택 제공",
  },
  {
    id: 3,
    title: "건강관리 지원",
    subTitle: "어르신 건강검진 및 지원 서비스",
    bookMark: false,
    category: "의료",
    content: "지원내용: 정기 건강검진과 맞춤형 건강관리 서비스 제공",
  },
  {
    id: 4,
    title: "생활 안전 지원",
    subTitle: "노인을 위한 주거 환경 개선",
    bookMark: true,
    category: "복지",
    content: "지원내용: 노후 주거 환경 개선을 위한 지원",
  },
  {
    id: 5,
    title: "평생교육 지원",
    subTitle: "어르신 디지털 교육 프로그램",
    bookMark: false,
    category: "근로",
    content: "지원내용: 디지털 격차 해소를 위한 교육 프로그램 운영",
  },
  {
    id: 6,
    title: "어르신 돌봄 서비스",
    subTitle: "취약계층 어르신 돌봄 지원",
    bookMark: false,
    category: "복지",
    content: "지원내용: 취약계층 노인을 위한 돌봄 서비스 제공",
  },
  {
    id: 7,
    title: "안전한 노후생활",
    subTitle: "어르신 낙상 예방 캠페인",
    bookMark: true,
    category: "근로",
    content: "지원내용: 낙상 예방 교육 및 생활 안전 강화",
  },
  {
    id: 8,
    title: "건강한 식생활 지원",
    subTitle: "노인을 위한 균형 잡힌 식단 제공",
    bookMark: false,
    category: "보건",
    content: "지원내용: 균형 잡힌 영양식 제공 및 식생활 개선",
  },
  {
    id: 9,
    title: "노인 맞춤형 체육 프로그램",
    subTitle: "어르신 건강 체육 활동 지원",
    bookMark: true,
    category: "의료",
    content: "지원내용: 체육 활동을 통한 건강 증진 지원",
  },
  {
    id: 10,
    title: "노인 정신건강 지원",
    subTitle: "우울증 및 고독사 예방",
    bookMark: false,
    category: "보건",
    content: "지원내용: 정신건강 상담 및 예방 프로그램 운영",
  },
  {
    id: 11,
    title: "주거 환경 개선 프로젝트",
    subTitle: "어르신 안전 주택 지원",
    bookMark: true,
    category: "복지",
    content: "지원내용: 어르신 주거 안정성을 위한 주택 개선 지원",
  },
  {
    id: 12,
    title: "노인 교통안전 캠페인",
    subTitle: "어르신 교통사고 예방 활동",
    bookMark: false,
    category: "근로",
    content: "지원내용: 교통사고 예방 교육 및 캠페인 진행",
  },
  {
    id: 13,
    title: "디지털 격차 해소 교육",
    subTitle: "어르신 디지털 기기 사용법 교육",
    bookMark: true,
    category: "근로",
    content: "지원내용: 디지털 기기 활용 능력 향상 지원",
  },
  {
    id: 14,
    title: "노인 여가 활동 지원",
    subTitle: "문화 공연 및 여행 프로그램",
    bookMark: false,
    category: "복지",
    content: "지원내용: 문화 공연과 여행 기회를 제공하여 여가 생활 지원",
  },
  {
    id: 15,
    title: "응급 상황 대비 서비스",
    subTitle: "어르신 응급벨 설치 지원",
    bookMark: true,
    category: "의료",
    content: "지원내용: 응급 상황에 대비한 안전 장비 설치 지원",
  },
  {
    id: 16,
    title: "노인 일자리 창출",
    subTitle: "어르신 맞춤형 일자리 지원",
    bookMark: false,
    category: "근로",
    content: "지원내용: 맞춤형 일자리 제공으로 노인 경제활동 지원",
  },
  {
    id: 17,
    title: "노인 학대 예방 캠페인",
    subTitle: "어르신 보호 및 지원 서비스",
    bookMark: true,
    category: "보건",
    content: "지원내용: 노인 학대 예방 및 보호를 위한 캠페인 운영",
  },
  {
    id: 18,
    title: "사회적 고립 예방 프로그램",
    subTitle: "노인 커뮤니티 활동 지원",
    bookMark: false,
    category: "교육문화",
    content: "지원내용: 노인들의 사회적 고립을 방지하기 위한 커뮤니티 프로그램",
  },
  {
    id: 19,
    title: "치매 예방 및 관리",
    subTitle: "어르신 치매 예방 프로그램",
    bookMark: false,
    category: "의료",
    content: "지원내용: 치매 예방 및 관리를 위한 전문 프로그램 제공",
  },
];
