export const dummyData = [
  {
    id: 1,
    title: "어르신 지원정책 모음",
    subTitle: "노인 생활안전사고 예방 지원정책",
    bookMark: false,
    category: "복지",
    startDate: "25.02.01",
    endDate: "25.03.01",
    fee: 0,
    registration: "100세누리 온라인 신청",
    content: "지원내용: 노인 생활 안전사고 예방을 위한 맞춤형 지원 제공",
  },
  {
    id: 2,
    title: "어르신 복지서비스",
    subTitle: "노인 대상 복지 혜택 모음",
    bookMark: true,
    category: "보건",
    startDate: "25.02.01",
    endDate: "25.03.01",
    fee: 0,
    registration: "복지센터 방문 신청",
    content: "지원내용: 노인 복지를 위한 다양한 혜택 제공",
  },
  {
    id: 3,
    title: "건강관리 지원",
    subTitle: "어르신 건강검진 및 지원 서비스",
    bookMark: false,
    category: "의료",
    startDate: "25.02.05",
    endDate: "25.04.05",
    fee: 5000,
    registration: "보건소 온라인 예약",
    content: "지원내용: 정기 건강검진과 맞춤형 건강관리 서비스 제공",
  },
  {
    id: 4,
    title: "생활 안전 지원",
    subTitle: "노인을 위한 주거 환경 개선",
    bookMark: true,
    category: "복지",
    startDate: "25.03.01",
    endDate: "25.06.01",
    fee: 0,
    registration: "구청 복지과 신청",
    content: "지원내용: 노후 주거 환경 개선을 위한 지원",
  },
  {
    id: 5,
    title: "평생교육 지원",
    subTitle: "어르신 디지털 교육 프로그램",
    bookMark: false,
    category: "근로",
    startDate: "25.03.10",
    endDate: "25.05.10",
    fee: 10000,
    registration: "교육센터 홈페이지 신청",
    content: "지원내용: 디지털 격차 해소를 위한 교육 프로그램 운영",
  },
  {
    id: 6,
    title: "어르신 돌봄 서비스",
    subTitle: "취약계층 어르신 돌봄 지원",
    bookMark: false,
    category: "복지",
    startDate: "25.02.15",
    endDate: "25.07.15",
    fee: 0,
    registration: "복지센터 방문 신청",
    content: "지원내용: 취약계층 노인을 위한 돌봄 서비스 제공",
  },
  {
    id: 7,
    title: "안전한 노후생활",
    subTitle: "어르신 낙상 예방 캠페인",
    bookMark: true,
    category: "근로",
    startDate: "25.04.01",
    endDate: "25.05.31",
    fee: 0,
    registration: "건강센터 온라인 신청",
    content: "지원내용: 낙상 예방 교육 및 생활 안전 강화",
  },
  {
    id: 8,
    title: "건강한 식생활 지원",
    subTitle: "노인을 위한 균형 잡힌 식단 제공",
    bookMark: false,
    category: "보건",
    startDate: "25.02.20",
    endDate: "25.06.20",
    fee: 3000,
    registration: "복지관 신청",
    content: "지원내용: 균형 잡힌 영양식 제공 및 식생활 개선",
  },
  {
    id: 9,
    title: "노인 맞춤형 체육 프로그램",
    subTitle: "어르신 건강 체육 활동 지원",
    bookMark: true,
    category: "의료",
    startDate: "25.03.15",
    endDate: "25.07.15",
    fee: 0,
    registration: "체육관 방문 신청",
    content: "지원내용: 체육 활동을 통한 건강 증진 지원",
  },
  {
    id: 10,
    title: "노인 정신건강 지원",
    subTitle: "우울증 및 고독사 예방",
    bookMark: false,
    category: "보건",
    startDate: "25.02.10",
    endDate: "25.08.10",
    fee: 0,
    registration: "보건소 상담 신청",
    content: "지원내용: 정신건강 상담 및 예방 프로그램 운영",
  },
];
