import imgTest from "../assets/images/img-test.png";

export const dummyData = [
  {
    id: 1,
    title: "어르신 지원정책 모음",
    subTitle: "노인 생활안전사고 예방 지원정책",
    assign: "고용노동부",
    bookMark: false,
    image: imgTest,
    dDay: 9,
    category: "복지",
  },
  {
    id: 2,
    title: "어르신 복지서비스",
    subTitle: "노인 대상 복지 혜택 모음",
    assign: "보건복지부",
    bookMark: true,
    image: imgTest,
    dDay: 5,
    category: "보건",
  },
  {
    id: 3,
    title: "건강관리 지원",
    subTitle: "어르신 건강검진 및 지원 서비스",
    assign: "질병관리청",
    bookMark: false,
    image: imgTest,
    dDay: 12,
    category: "의료",
  },
  {
    id: 4,
    title: "생활 안전 지원",
    subTitle: "노인을 위한 주거 환경 개선",
    assign: "국토교통부",
    bookMark: true,
    image: imgTest,
    dDay: 7,
    category: "복지",
  },
  {
    id: 5,
    title: "평생교육 지원",
    subTitle: "어르신 디지털 교육 프로그램",
    assign: "교육부",
    bookMark: false,
    image: imgTest,
    dDay: 3,
    category: "근로",
  },
  {
    id: 6,
    title: "어르신 돌봄 서비스",
    subTitle: "취약계층 어르신 돌봄 지원",
    assign: "보건복지부",
    bookMark: false,
    image: imgTest,
    dDay: 1,
    category: "복지",
  },
  {
    id: 7,
    title: "안전한 노후생활",
    subTitle: "어르신 낙상 예방 캠페인",
    assign: "고용노동부",
    bookMark: true,
    image: imgTest,
    dDay: 0,
    category: "근로",
  },
  {
    id: 8,
    title: "건강한 식생활 지원",
    subTitle: "노인을 위한 균형 잡힌 식단 제공",
    assign: "농림축산식품부",
    bookMark: false,
    image: imgTest,
    dDay: 2,
    category: "보건",
  },
  {
    id: 9,
    title: "노인 맞춤형 체육 프로그램",
    subTitle: "어르신 건강 체육 활동 지원",
    assign: "문화체육관광부",
    bookMark: true,
    image: imgTest,
    dDay: 1,
    category: "의료",
  },
  {
    id: 10,
    title: "노인 정신건강 지원",
    subTitle: "우울증 및 고독사 예방",
    assign: "보건복지부",
    bookMark: false,
    image: imgTest,
    dDay: 1,
    category: "보건",
  },
  {
    id: 11,
    title: "주거 환경 개선 프로젝트",
    subTitle: "어르신 안전 주택 지원",
    assign: "국토교통부",
    bookMark: true,
    image: imgTest,
    dDay: 6,
    category: "복지",
  },
  {
    id: 12,
    title: "노인 교통안전 캠페인",
    subTitle: "어르신 교통사고 예방 활동",
    assign: "경찰청",
    bookMark: false,
    image: imgTest,
    dDay: 8,
    category: "근로",
  },
  {
    id: 13,
    title: "디지털 격차 해소 교육",
    subTitle: "어르신 디지털 기기 사용법 교육",
    assign: "과학기술정보통신부",
    bookMark: true,
    image: imgTest,
    dDay: 10,
    category: "근로",
  },
  {
    id: 14,
    title: "노인 여가 활동 지원",
    subTitle: "문화 공연 및 여행 프로그램",
    assign: "문화체육관광부",
    bookMark: false,
    image: imgTest,
    dDay: 3,
    category: "복지",
  },
  {
    id: 15,
    title: "응급 상황 대비 서비스",
    subTitle: "어르신 응급벨 설치 지원",
    assign: "소방청",
    bookMark: true,
    image: imgTest,
    dDay: 4,
    category: "의료",
  },
  {
    id: 16,
    title: "노인 일자리 창출",
    subTitle: "어르신 맞춤형 일자리 지원",
    assign: "고용노동부",
    bookMark: false,
    image: imgTest,
    dDay: 2,
    category: "근로",
  },
  {
    id: 17,
    title: "노인 학대 예방 캠페인",
    subTitle: "어르신 보호 및 지원 서비스",
    assign: "보건복지부",
    bookMark: true,
    image: imgTest,
    dDay: 11,
    category: "보건",
  },
  {
    id: 18,
    title: "사회적 고립 예방 프로그램",
    subTitle: "노인 커뮤니티 활동 지원",
    assign: "보건복지부",
    bookMark: false,
    image: imgTest,
    dDay: 5,
    category: "복지",
  },
  {
    id: 19,
    title: "치매 예방 및 관리",
    subTitle: "어르신 치매 예방 프로그램",
    assign: "질병관리청",
    bookMark: false,
    image: imgTest,
    dDay: 0,
    category: "의료",
  },
  {
    id: 20,
    title: "어르신 건강보험 혜택",
    subTitle: "노인 의료비 지원 정책",
    assign: "국민건강보험공단",
    bookMark: true,
    image: imgTest,
    dDay: 9,
    category: "의료",
  },
]