export const noImageData = [
  {
    id: 1,
    title: "어르신 지원정책 모음",
    subTitle: "노인 생활안전사고 예방 지원정책",
    assign: "고용노동부",
    bookMark: false,
    category: "복지",
    duration: "01.01 ~ 01.15",
    city: "서울특별시",
  },
  {
    id: 2,
    title: "어르신 복지서비스",
    subTitle: "노인 대상 복지 혜택 모음",
    assign: "보건복지부",
    bookMark: true,
    category: "보건",
    duration: "01.05 ~ 01.20",
    city: "부산광역시",
  },
  {
    id: 3,
    title: "건강관리 지원",
    subTitle: "어르신 건강검진 및 지원 서비스",
    assign: "보건소",
    bookMark: false,
    category: "의료",
    duration: "01.10 ~ 01.25",
    city: "대구광역시",
  },
  {
    id: 4,
    title: "중소기업 지원 정책",
    subTitle: "중소기업을 위한 정부 지원 혜택",
    assign: "중소기업청",
    bookMark: false,
    category: "경제",
    duration: "01.01 ~ 12.31",
    city: "인천광역시",
  },
  {
    id: 5,
    title: "장애인 생활 지원 정책",
    subTitle: "장애인을 위한 맞춤형 생활 지원 정책",
    assign: "복지센터",
    bookMark: false,
    category: "복지",
    duration: "02.15 ~ 12.31",
    city: "광주광역시",
  },
    
    // 보여주기용 데이터
  {
    id: 6,
    title: "어르신 돌봄 서비스",
    subTitle: "취약계층 어르신 돌봄 지원",
    assign: "보건복지부",
    bookMark: false,
    category: "복지",
    duration: "01.02 ~ 01.16",
    city: "대전광역시",
  },
  {
    id: 7,
    title: "안전한 노후생활",
    subTitle: "어르신 낙상 예방 캠페인",
    assign: "고용노동부",
    bookMark: true,
    category: "근로",
    duration: "01.07 ~ 01.21",
    city: "울산광역시",
  },
  {
    id: 8,
    title: "건강한 식생활 지원",
    subTitle: "노인을 위한 균형 잡힌 식단 제공",
    assign: "농림축산식품부",
    bookMark: false,
    category: "보건",
    duration: "01.04 ~ 01.18",
    city: "세종특별자치시",
  },
  {
    id: 9,
    title: "노인 맞춤형 체육 프로그램",
    subTitle: "어르신 건강 체육 활동 지원",
    assign: "문화체육관광부",
    bookMark: true,
    category: "의료",
    duration: "01.06 ~ 01.20",
    city: "경기도",
  },
  {
    id: 10,
    title: "노인 정신건강 지원",
    subTitle: "우울증 및 고독사 예방",
    assign: "보건복지부",
    bookMark: false,
    category: "보건",
    duration: "01.09 ~ 01.23",
    city: "강원도",
  },
  {
    id: 11,
    title: "주거 환경 개선 프로젝트",
    subTitle: "어르신 안전 주택 지원",
    assign: "국토교통부",
    bookMark: true,
    category: "복지",
    duration: "01.11 ~ 01.25",
    city: "충청북도",
  },
  {
    id: 12,
    title: "노인 교통안전 캠페인",
    subTitle: "어르신 교통사고 예방 활동",
    assign: "경찰청",
    bookMark: false,
    category: "근로",
    duration: "01.12 ~ 01.26",
    city: "충청남도",
  },
  {
    id: 13,
    title: "디지털 격차 해소 교육",
    subTitle: "어르신 디지털 기기 사용법 교육",
    assign: "과학기술정보통신부",
    bookMark: true,
    category: "근로",
    duration: "01.14 ~ 01.28",
    city: "전라북도",
  },
  {
    id: 14,
    title: "노인 여가 활동 지원",
    subTitle: "문화 공연 및 여행 프로그램",
    assign: "문화체육관광부",
    bookMark: false,
    category: "복지",
    duration: "01.15 ~ 01.29",
    city: "전라남도",
  },
  {
    id: 15,
    title: "응급 상황 대비 서비스",
    subTitle: "어르신 응급벨 설치 지원",
    assign: "소방청",
    bookMark: true,
    category: "의료",
    duration: "01.13 ~ 01.27",
    city: "경상북도",
  },
  {
    id: 16,
    title: "노인 일자리 창출",
    subTitle: "어르신 맞춤형 일자리 지원",
    assign: "고용노동부",
    bookMark: false,
    category: "근로",
    duration: "01.08 ~ 01.22",
    city: "경상남도",
  },
  {
    id: 17,
    title: "노인 학대 예방 캠페인",
    subTitle: "어르신 보호 및 지원 서비스",
    assign: "보건복지부",
    bookMark: true,
    category: "보건",
    duration: "01.16 ~ 01.30",
    city: "제주특별자치도",
  },
  {
    id: 18,
    title: "사회적 고립 예방 프로그램",
    subTitle: "노인 커뮤니티 활동 지원",
    assign: "보건복지부",
    bookMark: false,
    category: "교육문화",
    duration: "01.18 ~ 02.01",
    city: "서울특별시",
  },
  {
    id: 19,
    title: "치매 예방 및 관리",
    subTitle: "어르신 치매 예방 프로그램",
    assign: "질병관리청",
    bookMark: false,
    category: "의료",
    duration: "01.20 ~ 02.03",
    city: "부산광역시",
  },
];
