export const questionData = [
  {
    id: "start",
    question: "누구를 위해 정책을 찾고 계신가요?",
    options: [
      { text: "나를 위한 정책", nextId: "location" },
      { text: "부모님/가족을 위한 정책", nextId: "familyLocation" },
      { text: "내가 담당하는 어르신을 위한 정책", nextId: "familyLocation" },
    ],
  },

  {
    id: "location",
    question: "현재 거주지역은 어디인가요?",
    options: [
      { text: "서울", nextId: "needs" },
      { text: "경기도", nextId: "needs" },
      { text: "인천", nextId: "needs" },
      { text: "부산", nextId: "needs" },
      { text: "충청북도", nextId: "needs" },
      { text: "충청남도", nextId: "needs" },
      { text: "전라북도", nextId: "needs" },
      { text: "전라남도", nextId: "needs" },
      { text: "경상북도", nextId: "needs" },
      { text: "경상남도", nextId: "needs" },
      { text: "강원도", nextId: "needs" },
      { text: "제주도", nextId: "needs" },
    ],
  },
  {
    id: "needs",
    question: "현재 필요한 지원은 무엇인가요?",
    options: [
      { text: "신체건강", nextId: "Situation" },
      { text: "정신건강", nextId: "Situation" },
      { text: "생활지원", nextId: "Situation" },
      { text: "주거", nextId: "Situation" },
      { text: "일자리", nextId: "Situation" },
      { text: "문화·여가", nextId: "Situation" },
      { text: "안전·위기", nextId: "Situation" },
      { text: "임신·출산", nextId: "Situation" },
      { text: "보육", nextId: "Situation" },
      { text: "교육", nextId: "Situation" },
      { text: "입양·위착", nextId: "Situation" },
      { text: "보호·돌봄", nextId: "Situation" },
      { text: "서민금융", nextId: "Situation" },
      { text: "법률", nextId: "Situation" },
    ],
  },
  {
    id: "Situation",
    question: "현재 어떤 가구 상황에 해당되시나요?",
    options: [
      { text: "다문화·탈북민", nextId: "disability" },
      { text: "다자녀", nextId: "disability" },
      { text: "보훈대상자", nextId: "disability" },
      { text: "장애인", nextId: "disability" },
      { text: "저소득", nextId: "disability" },
      { text: "한부모·조손", nextId: "disability" },
      { text: "해당 없음", nextId: "disability" },
    ],
  },
  {
    id: "disability",
    question: "만약 장애가 있으시다면, 장애 정도는 어떤가요?",
    options: [
      { text: "장애 미해당", nextId: "null" },
      { text: "심한 장애", nextId: "null" },
      { text: "심하지 않은 장애", nextId: "null" },
      { text: "결정보류", nextId: "null" },
      { text: "확인불가", nextId: "null" },
    ],
  },
  {
    id: "familyLocation",
    question: "부양하거나 돕고 있는 어르신은 현재 어느 지역에 거주하시나요?",
    options: [
      { text: "서울", nextId: "familyNeeds" },
      { text: "경기도", nextId: "familyNeeds" },
      { text: "인천", nextId: "familyNeeds" },
      { text: "부산", nextId: "familyNeeds" },
      { text: "충청북도", nextId: "familyNeeds" },
      { text: "충청남도", nextId: "familyNeeds" },
      { text: "전라북도", nextId: "familyNeeds" },
      { text: "전라남도", nextId: "familyNeeds" },
      { text: "경상북도", nextId: "familyNeeds" },
      { text: "경상남도", nextId: "familyNeeds" },
      { text: "강원도", nextId: "familyNeeds" },
      { text: "제주도", nextId: "familyNeeds" },
    ],
  },
  {
    id: "familyNeeds",
    question: "어르신께 현재 필요한 지원은 무엇인가요?",
    options: [
      { text: "신체건강", nextId: "familySituation" },
      { text: "정신건강", nextId: "familySituation" },
      { text: "생활지원", nextId: "familySituation" },
      { text: "주거", nextId: "familySituation" },
      { text: "일자리", nextId: "familySituation" },
      { text: "문화·여가", nextId: "familySituation" },
      { text: "안전·위기", nextId: "familySituation" },
      { text: "임신·출산", nextId: "familySituation" },
      { text: "보육", nextId: "familySituation" },
      { text: "교육", nextId: "familySituation" },
      { text: "입양·위착", nextId: "familySituation" },
      { text: "보호·돌봄", nextId: "familySituation" },
      { text: "서민금융", nextId: "familySituation" },
      { text: "법률", nextId: "familySituation" },
    ],
  },
  {
    id: "familySituation",
    question: "어르신께서 현재 어떤 가구에 해당 되시나요?",
    options: [
      { text: "다문화·탈북민", nextId: "familyDisability" },
      { text: "다자녀", nextId: "familyDisability" },
      { text: "보훈대상자", nextId: "familyDisability" },
      { text: "장애인", nextId: "familyDisability" },
      { text: "저소득", nextId: "familyDisability" },
      { text: "한부모·조손", nextId: "familyDisability" },
      { text: "해당 없음", nextId: "familyDisability" },
    ],
  },
  {
    id: "familyDisability",
    question: "만약 장애가 있으시다면, 어르신의 장애 정도는 어떤가요?",
    options: [
      { text: "장애 미해당", nextId: "null" },
      { text: "심한 장애", nextId: "null" },
      { text: "심하지 않은 장애", nextId: "null" },
      { text: "결정보류", nextId: "null" },
      { text: "확인불가", nextId: "null" },
    ],
  },
];