export const pagePath = {
  HOME: "home",
  POLICY : 'policy',
  EVENT : 'event',
  EVENTDETAIL : 'event/:eventId',
  JOB: 'job',
  SUPPORT : 'support',
  LOGIN : 'login',
  SIGNUP : 'signup',
  MYPAGE : 'mypage',
  FINDEMAIL : 'find-email',
  FINDPASSWORD : 'find-password',
  EMAILRESULT : 'email-result',
  PASSWORDSENT : 'password-sent',
}
