const dummy = {
  치료: [
    {
      category: "정책",
      title: "치료 정책 1",
      method: "· 온라인 예약",
      location: "서울병원 101호",
      remainingPeriod: "3일",
    },
    {
      category: "정책",
      title: "치료 정책 2",
      method: "· 전화 상담",
      location: "부산병원 202호",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 1",
      location: "서울센터",
      remainingPeriod: "7일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 2",
      method: "· 전화 상담",
      location: "인천센터",
      remainingPeriod: "10일",
    },
    {
      category: "정책",
      title: "치료 정책 1",
      method: "온라인 예약",
      location: "서울병원 101호",
      remainingPeriod: "3일",
    },
    {
      category: "정책",
      title: "치료 정책 2",
      method: "· 전화 상담",
      location: "부산병원 202호",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 1",
      method: "· 전화 상담",
      location: "서울센터",
      remainingPeriod: "7일",
    },
    {
      category: "정책",
      title: "치료 정책 1",
      method: "· 온라인 예약",
      location: "서울병원 101호",
      remainingPeriod: "3일",
    },
    {
      category: "정책",
      title: "치료 정책 2",
      method: "· 전화 상담",
      location: "부산병원 202호",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 1",
      location: "서울센터",
      remainingPeriod: "7일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 2",
      method: "· 전화 상담",
      location: "인천센터",
      remainingPeriod: "10일",
    },
    {
      category: "정책",
      title: "치료 정책 1",
      method: "온라인 예약",
      location: "서울병원 101호",
      remainingPeriod: "3일",
    },
    {
      category: "정책",
      title: "치료 정책 2",
      method: "· 전화 상담",
      location: "부산병원 202호",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "치료 교육 세미나 1",
      method: "· 전화 상담",
      location: "서울센터",
      remainingPeriod: "7일",
    },
  ],
  수술: [
    {
      category: "정책",
      title: "수술 정책 1",
      method: "진료 예약",
      location: "서울병원 303호",
      remainingPeriod: "1일",
    },
    {
      category: "정책",
      title: "수술 정책 2",
      method: "직접 방문",
      location: "대구병원 405호",
      remainingPeriod: "2일",
    },
    {
      category: "행사/교육",
      title: "수술 교육 세미나 1",
      method: "· 전화 상담",
      location: "대전센터",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "수술 교육 세미나 2",
      method: "· 전화 상담",
      location: "광주센터",
      remainingPeriod: "8일",
    },
    {
      category: "정책",
      title: "수술 정책 1",
      method: "진료 예약",
      location: "서울병원 303호",
      remainingPeriod: "1일",
    },
    {
      category: "정책",
      title: "수술 정책 2",
      method: "직접 방문",
      location: "대구병원 405호",
      remainingPeriod: "2일",
    },
    {
      category: "행사/교육",
      title: "수술 교육 세미나 1",
      method: "· 전화 상담",
      location: "대전센터",
      remainingPeriod: "5일",
    },
    {
      category: "행사/교육",
      title: "수술 교육 세미나 2",
      method: "· 전화 상담",
      location: "광주센터",
      remainingPeriod: "8일",
    },
  ],
};

export default dummy;
